[package]
name = "denox"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "denox"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
deno_core = "0.341.0"
tokio = { version = "1.43", features = ["full"] }
