[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]
